export const routes = {
  user: {
    home: "/",
    profile: "/user/profile",
    signUp: "/user/signup",
    jobs: "/user/jobs",
    chat: "/user/chats",
    applyJob: "/user/jobs/apply",
    hired: "/user/jobs/hired",
    saveJob: "/user/jobs/save",
    request: "/user/jobs/request",
    forgetPassword: "/user/forgotpassword",
    login: "/user/login",
    map: "/user/map",
    docs: "/user/docs",
  },
  company: {
    home: "/company",
    profile: "/company/profile",
    jobCreate: "/company/job/create",
    jobs: "/company/job",
    create: "/company/job/create",
    save: "/company/users/save",
    update_job: "/company/job/update",
    chat: "/company/chats",
    forgetPassword: "/company/forgotpassword",
    users: "/company/users",
    request: "/company/users/request",
    hired: "/company/users/hired",
    signUp: "/company/signup",
    login: "/company/login",
    docs: "/company/docs",
  },
};
