export const jsFrameworks: Array<string> =   [
  "Dog",
  "Cat",
  "Bird",
  "Fish",
  "Hamster",
  "Guinea Pig",
  "Rabbit",
  "Turtle",
  "Canary",
  "Parakeet",
  "Mouse",
  "Ferret",
  "Gerbil",
  "Hedgehog",
  "Snake (in some cases)",
  "Lizard (in some cases)"
];


export const jobWorkingStyles: Array<string> =[
  "Nocturnal",
  "Diurnal",
  "Crepuscular",
  "Hibernates in winter",
  "Migratory",
  "Burrowing",
  "Gregarious",
  "Solitary",
  "Territorial",
  "Nest-building",
  "Hunting in packs",
  "Camouflaging",
  "Mimicking",
  "Migrates for breeding",
  "Hibernate during summer",
  "Marking territory",
  "Swarming",
  "Moulting",
  "Predatory",
  "Scavenging"
];

export const spokenLanguages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Japanese",
  "Chinese",
  "Korean",
  "Arabic",
  "Hindi",
  "Bengali",
  "Swahili",
  "Swedish",
  "Danish",
  "Greek",
  "Turkish",
  "Vietnamese",
];
