export const jsFrameworks: Array<string> = [
  "AngularJS",
  "ReactJS",
  "Vue.js",
  "Ember.js",
  "Backbone.js",
  "Meteor.js",
  "Knockout.js",
  "Polymer.js",
  "Aurelia.js",
  "Svelte.js",
  "JavaScript",
  "TypeScript",
  "CoffeeScript",
  "Dart",
  "Elm",
  "PureScript",
  "ReasonML",
  "ClojureScript",
  "Haxe",
  "WebAssembly",
];

export const jobWorkingStyles: Array<string> = [
  "Full-time",
  "Part-time",
  "Freelance",
  "Contract",
  "Temporary",
  "Internship",
  "Remote",
  "Flex-time",
  "Shift-work",
  "Job-sharing",
];

export const spokenLanguages = [
  "English",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Dutch",
  "Russian",
  "Japanese",
  "Chinese",
  "Korean",
  "Arabic",
  "Hindi",
  "Bengali",
  "Swahili",
  "Swedish",
  "Danish",
  "Greek",
  "Turkish",
  "Vietnamese",
];
